# FUNDING.yml for the Philosophy of the Machines
# Add your donation link(s) below

# PayPal donate link (replace with your actual ID)
custom: ['https://www.paypal.com/donate/?hosted_button_id=BKH7H2T3VBAE6']
